# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNSprofileImage-Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNSprofileImage-Sample

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'IQKeyboardManagerSwift'
  pod 'RSKImageCropper'


  target 'SNSprofileImage-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SNSprofileImage-SampleUITests' do
    # Pods for testing
  end

end
